services:
  # Base PostgreSQL
  postgres:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_USER: jemath
      POSTGRES_PASSWORD: apghma
      POSTGRES_DB: studentgestion
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Interface web pour la DB
  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8082:8080"

volumes:
  pgdata: