spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5433/studentgestion
    username: jemath
    password: apghma
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

server:
  port: 8081

logging:
  level:
    root: error
    "[fr.afpa.brive.cda]": debug
    "[org.springframework.data]": info
    "[org.springframework.jdbc.core.JdbcTemplate]": debug
    "[org.springframework.boot.web.embedded.tomcat]": info
