### CREATE ADMIN
POST http://localhost:8081/api/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZHVwb250IiwiaWF0IjoxNzYzNDYwMzkwLCJleHAiOjE3NjM0NjM5OTB9.KPEHr_DGF7GD5KQc0T_YZnUTvNq2HKuhn7s2dR-5Pdk

{
  "firstname": "Sophie",
  "lastname": "Martin",
  "username": "smartin",
  "email": "sophie.martin@school.fr",
  "password": "Teacher123!",
  "phoneNumber": "0600000001",
  "postalAddress": "1 rue de l'École",
  "role": "TEACHER",
  "teachingsIds": [100],
  "childrenIds": []
}

### Test méthode autorisée
POST http://localhost:8081/api/login
Content-Type: application/json

{
  "username": "jdupont",
  "password": "Admin#2025"
}
